"""
Author: Vinaya Sathyanarayana

Clustering Demo Program using Synthetic Financial Data for Masters Course

This program demonstrates the usage of various clustering algorithms 
on synthetic financial customer data generated by syntheticdata.csv.

Features:
- Loads syntheticdata.csv with multiple data types (numerical, categorical, text, dates)
- Demonstrates key clustering techniques:
  * Distance-based (KMeans)
  * Density-based (DBSCAN)
  * Probabilistic (Gaussian Mixture Models)
  * Dimensionality Reduction + Clustering (PCA + KMeans)
- Supports numerical and categorical data clustering via encoding and scaling
- Visualizations for cluster distributions, silhouette analysis, PCA projection
- Step-by-step explanations provided via printed messages
- Model comparisons via metrics: Silhouette Score, Calinski-Harabasz Index, Davies-Bouldin Index
- Extensive error handling and user instructions included

Instructions for students:
- Ensure syntheticdata.csv is available in the same directory
- Install required packages: `pip install -r requirements.txt`
- Run this script: `python clusteringdemo.py`
- Explore parameters inside main() to tune clustering hyperparameters
- View and interpret plots and metrics to understand clustering quality

Instructions for banks:
- The demo illustrates how banks can segment customers using clustering on transaction, risk, and demographic data
- Use similar workflows with proprietary data to inform marketing, risk management, and customer relationship strategies
- Evaluate algorithms and tune hyperparameters for best fit to their business goals

"""

import sys
import traceback
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.cluster import KMeans, DBSCAN
from sklearn.mixture import GaussianMixture
from sklearn.metrics import silhouette_score, calinski_harabasz_score, davies_bouldin_score
from sklearn.decomposition import PCA

def load_data(filepath='syntheticdata.csv'):
    """
    Load synthetic data from CSV file.
    """
    try:
        df = pd.read_csv(filepath, parse_dates=['Account_Open_Date', 'Transaction_Date'])
        print(f"Loaded dataset with {df.shape[0]} rows and {df.shape[1]} columns.")
        return df
    except FileNotFoundError:
        print(f"Error: File {filepath} not found. Please generate syntheticdata.csv first.")
        sys.exit(1)
    except Exception as e:
        print("Error loading data:", e)
        traceback.print_exc()
        sys.exit(1)

def preprocess_data(df):
    """
    Preprocess data for clustering:
    - Encode categorical columns using OneHotEncoder
    - Scale numerical columns using StandardScaler
    - Select relevant columns for clustering demonstration
    """
    try:
        # Columns chosen for clustering demonstration
        numerical_features = ['Age', 'Income_INR', 'Transaction_Amount_INR', 'Risk_Score', 'Monthly_Transactions', 'Monthly_Volume_INR']
        categorical_features = ['Gender', 'Account_Type', 'Transaction_Type', 'Feedback']

        # We drop identifiers and text columns (Name, City, State, Account_ID, Segment)
        df_cluster = df[numerical_features + categorical_features].copy()

        # Column Transformer to apply preprocessing pipelines
        preprocessor = ColumnTransformer(
            transformers=[
                ('num', StandardScaler(), numerical_features),
                ('cat', OneHotEncoder(drop='first'), categorical_features)
            ]
        )
        data_processed = preprocessor.fit_transform(df_cluster)
        print(f"Preprocessed data shape (after encoding and scaling): {data_processed.shape}")
        return data_processed, preprocessor
    except Exception as e:
        print("Error during preprocessing:", e)
        traceback.print_exc()
        sys.exit(1)

def run_kmeans(data, n_clusters=3):
    """
    Run KMeans clustering.
    """
    kmeans = KMeans(n_clusters=n_clusters, random_state=42)
    clusters = kmeans.fit_predict(data)
    print(f"KMeans: Found {n_clusters} clusters.")
    return kmeans, clusters

def run_dbscan(data, eps=0.5, min_samples=5):
    """
    Run DBSCAN clustering.
    """
    dbscan = DBSCAN(eps=eps, min_samples=min_samples)
    clusters = dbscan.fit_predict(data)
    n_clusters = len(set(clusters)) - (1 if -1 in clusters else 0)
    print(f"DBSCAN: Found {n_clusters} clusters (excluding noise).")
    return dbscan, clusters

def run_gmm(data, n_components=3):
    """
    Run Gaussian Mixture Model clustering.
    """
    gmm = GaussianMixture(n_components=n_components, random_state=42)
    clusters = gmm.fit_predict(data)
    print(f"GMM: Found {n_components} mixture components.")
    return gmm, clusters

def run_pca(data, n_components=2):
    """
    Dimensionality reduction using PCA for visualization.
    """
    pca = PCA(n_components=n_components, random_state=42)
    data_pca = pca.fit_transform(data)
    explained_var = pca.explained_variance_ratio_.sum()
    print(f"PCA: Reduced data to {n_components} dimensions capturing {explained_var:.2%} variance.")
    return pca, data_pca

def evaluate_clustering(data, clusters):
    """
    Evaluate clustering using common metrics.
    Silhouette Score: higher is better; range [-1,1]
    Calinski-Harabasz Index: higher is better
    Davies-Bouldin Index: lower is better
    """
    # If only 1 cluster or all noise, metrics are not meaningful
    if len(set(clusters)) <= 1 or (len(set(clusters)) == 2 and -1 in clusters):
        return {'silhouette': np.nan, 'calinski_harabasz': np.nan, 'davies_bouldin': np.nan}

    silhouette = silhouette_score(data, clusters)
    ch_score = calinski_harabasz_score(data, clusters)
    db_score = davies_bouldin_score(data, clusters)

    return {'silhouette': silhouette, 'calinski_harabasz': ch_score, 'davies_bouldin': db_score}

def plot_clusters(data_2d, clusters, title):
    """
    Plot cluster assignments on 2D data (e.g. PCA reduced)
    """
    plt.figure(figsize=(8,6))
    sns.scatterplot(x=data_2d[:,0], y=data_2d[:,1], hue=clusters, palette='Set1', legend='full', alpha=0.6)
    plt.title(title)
    plt.xlabel('Component 1')
    plt.ylabel('Component 2')
    plt.legend(title='Cluster')
    plt.show()

def print_instructions():
    """
    Print user instructions for using the clustering demo.
    """
    print("""
Clustering Demo Instructions:
- Data is preprocessed (scaled numerical, encoded categorical).
- KMeans, DBSCAN, and GMM algorithms are run on the data.
- PCA reduces data to 2D for visualization.
- Evaluation metrics guide quality interpretation.
- Try changing parameters like n_clusters (KMeans, GMM) or eps (DBSCAN).
- Visualize clusters on PCA components.
- Use cluster insights to identify customer segments for marketing/risk.
""")

def main():
    print("Starting Clustering Demonstration...")
    print_instructions()

    # Load synthetic data
    df = load_data()

    # Preprocess data for clustering
    data_processed, preprocessor = preprocess_data(df)

    # Step 1: KMeans clustering
    kmeans, kmeans_labels = run_kmeans(data_processed, n_clusters=3)
    kmeans_metrics = evaluate_clustering(data_processed, kmeans_labels)

    # Step 2: DBSCAN clustering with tuned eps
    dbscan, dbscan_labels = run_dbscan(data_processed, eps=1.5, min_samples=10)
    dbscan_metrics = evaluate_clustering(data_processed, dbscan_labels)

    # Step 3: Gaussian Mixture Model clustering
    gmm, gmm_labels = run_gmm(data_processed, n_components=3)
    gmm_metrics = evaluate_clustering(data_processed, gmm_labels)

    # Step 4: PCA reduction for visualization
    pca, data_2d = run_pca(data_processed, n_components=2)

    # Plot clusters on PCA components
    plot_clusters(data_2d, kmeans_labels, "KMeans Clusters on PCA Components")
    plot_clusters(data_2d, dbscan_labels, "DBSCAN Clusters on PCA Components")
    plot_clusters(data_2d, gmm_labels, "GMM Clusters on PCA Components")

    # Print evaluation results comparison table
    print("\nClustering Evaluation Metrics Comparison:")
    metrics_df = pd.DataFrame({
        'Algorithm': ['KMeans', 'DBSCAN', 'GMM'],
        'Silhouette Score': [kmeans_metrics['silhouette'], dbscan_metrics['silhouette'], gmm_metrics['silhouette']],
        'Calinski-Harabasz Index': [kmeans_metrics['calinski_harabasz'], dbscan_metrics['calinski_harabasz'], gmm_metrics['calinski_harabasz']],
        'Davies-Bouldin Index': [kmeans_metrics['davies_bouldin'], dbscan_metrics['davies_bouldin'], gmm_metrics['davies_bouldin']]
    })
    print(metrics_df.to_string(index=False))

    print("\nInterpretation:")
    print(" - Silhouette Score closer to 1 indicates well-separated clusters.")
    print(" - Higher Calinski-Harabasz Index indicates denser, well-separated clusters.")
    print(" - Lower Davies-Bouldin Index indicates better clustering quality.")
    print("Use these metrics alongside domain knowledge to select appropriate clustering model.\n")

if __name__ == "__main__":
    main()
