"""
Fraud Detection using Outlier Detection Techniques
Author: Vinaya Sathyanarayana

This program demonstrates fraud detection on synthetic credit card transaction data using:
- Statistical Method (Z-score based anomaly detection)
- Proximity-based Method (Local Outlier Factor)
- Reconstruction-based Method (Isolation Forest)

It loads syntheticdata.csv generated by the synthetic data generator program, applies the models,
evaluates them with precision, recall, F1, accuracy, shows confusion matrices, and plots graphs with explanations.

Instructions:
- Run after generating syntheticdata.csv with synthetic_data_generator.py
- Modify contamination parameters to tune detection sensitivity
- Explore feature selection in preprocess method

Output:
- Evaluation comparison table
- Confusion matrix heatmaps for each algorithm
- Explanation and guidance for using results in banking fraud management

"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor
from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score, confusion_matrix


class FraudOutlierDetection:
    def __init__(self, filename='syntheticdata.csv'):
        self.filename = filename
        self.data = None
        self.features = None
        self.labels = None

    def load_data(self):
        try:
            self.data = pd.read_csv(self.filename)
            print(f"Data loaded successfully. Shape: {self.data.shape}")
        except FileNotFoundError:
            raise FileNotFoundError(f"File {self.filename} not found. Please generate synthetic data first.")
        except Exception as e:
            raise RuntimeError(f"Error loading file {self.filename}: {e}")

    def preprocess(self):
        try:
            df = self.data.copy()
            df['transaction_date'] = pd.to_datetime(df['transaction_date'])
            # Extract useful time features
            df['hour'] = df['transaction_date'].dt.hour
            df['day_of_week'] = df['transaction_date'].dt.dayofweek

            # Encode categorical features
            df = pd.get_dummies(df, columns=['merchant_category', 'card_type', 'card_issuer'], drop_first=True)

            # Select features for modeling
            feature_cols = [
                'transaction_amount', 'hour', 'day_of_week'
            ] + [col for col in df.columns if col.startswith('merchant_category_') or
                 col.startswith('card_type_') or col.startswith('card_issuer_')]

            self.features = df[feature_cols]
            self.labels = df['is_fraud']
            print(f"Preprocessing done. Feature shape: {self.features.shape}")
        except Exception as e:
            raise RuntimeError(f"Error during preprocessing: {e}")

    def apply_statistical_method(self):
        try:
            amounts = self.features['transaction_amount']
            z_scores = (amounts - amounts.mean()) / amounts.std()
            preds = (np.abs(z_scores) > 3).astype(int)  # z-score > 3 considered outlier
            return preds
        except Exception as e:
            raise RuntimeError(f"Error in statistical method: {e}")

    def apply_lof(self):
        try:
            lof = LocalOutlierFactor(n_neighbors=20, contamination=0.02)
            preds = lof.fit_predict(self.features)
            preds = np.where(preds == -1, 1, 0)  # -1 outlier -> 1 fraud label
            return preds
        except Exception as e:
            raise RuntimeError(f"Error in Local Outlier Factor: {e}")

    def apply_isolation_forest(self):
        try:
            iso_forest = IsolationForest(contamination=0.02, random_state=42)
            iso_forest.fit(self.features)
            preds = iso_forest.predict(self.features)
            preds = np.where(preds == -1, 1, 0)
            return preds
        except Exception as e:
            raise RuntimeError(f"Error in Isolation Forest: {e}")

    def evaluate(self, y_true, y_pred):
        try:
            accuracy = accuracy_score(y_true, y_pred)
            precision = precision_score(y_true, y_pred, zero_division=0)
            recall = recall_score(y_true, y_pred, zero_division=0)
            f1 = f1_score(y_true, y_pred, zero_division=0)
            cm = confusion_matrix(y_true, y_pred)
            report = classification_report(y_true, y_pred, zero_division=0)
            return {
                'accuracy': accuracy,
                'precision': precision,
                'recall': recall,
                'f1_score': f1,
                'confusion_matrix': cm,
                'classification_report': report
            }
        except Exception as e:
            raise RuntimeError(f"Error during evaluation: {e}")

    def plot_confusion_matrix(self, cm, title):
        plt.figure(figsize=(5, 4))
        sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
        plt.xlabel('Predicted Label')
        plt.ylabel('True Label')
        plt.title(title)
        plt.show()

    def plot_class_distribution(self):
        plt.figure(figsize=(6, 4))
        sns.countplot(x=self.labels)
        plt.title('Class Distribution (0=Normal, 1=Fraud)')
        plt.show()

    def run(self):
        self.load_data()
        self.preprocess()

        # Apply outlier detection methods
        preds_stat = self.apply_statistical_method()
        preds_lof = self.apply_lof()
        preds_if = self.apply_isolation_forest()

        # Evaluate each
        eval_stat = self.evaluate(self.labels, preds_stat)
        eval_lof = self.evaluate(self.labels, preds_lof)
        eval_if = self.evaluate(self.labels, preds_if)

        # Display evaluation metrics table
        eval_df = pd.DataFrame({
            'Statistical Method': [eval_stat['accuracy'], eval_stat['precision'], eval_stat['recall'], eval_stat['f1_score']],
            'Local Outlier Factor': [eval_lof['accuracy'], eval_lof['precision'], eval_lof['recall'], eval_lof['f1_score']],
            'Isolation Forest': [eval_if['accuracy'], eval_if['precision'], eval_if['recall'], eval_if['f1_score']]
        }, index=['Accuracy', 'Precision', 'Recall', 'F1 Score'])

        print("\nModel Evaluation Comparison:")
        print(eval_df)

        # Plot class distribution
        self.plot_class_distribution()
        print("Explanation: Shows the imbalance between normal and fraud transactions. Fraud cases are significantly fewer.")

        # Plot confusion matrices
        self.plot_confusion_matrix(eval_stat['confusion_matrix'], 'Confusion Matrix - Statistical Method')
        print("Explanation: Displays true/false positives and negatives for Statistical Method fraud detection.")

        self.plot_confusion_matrix(eval_lof['confusion_matrix'], 'Confusion Matrix - Local Outlier Factor')
        print("Explanation: Displays confusion matrix for LOF method, a proximity-based anomaly detection.")

        self.plot_confusion_matrix(eval_if['confusion_matrix'], 'Confusion Matrix - Isolation Forest')
        print("Explanation: Shows performance of Isolation Forest, a reconstruction-based anomaly detection method.")

        # Self-service instructions for students
        print("\nStudent Instructions:")
        print("- Adjust contamination parameter in Isolation Forest and LOF to tune detection sensitivity.")
        print("- Experiment with feature engineering in the preprocess method (add/remove features).")
        print("- Try more advanced methods like Autoencoders for reconstruction-based detection.")
        print("- Analyze how precision and recall change with parameter tuning to handle trade-offs.")

        # Instructions for banks
        print("\nBank Usage Instructions:")
        print("- Use this program as a benchmarking tool on your transaction data.")
        print("- Customize features and parameters to fit your bank's transaction patterns.")
        print("- Use evaluation metrics and confusion matrices to balance fraud detection and false alarms.")
        print("- Leverage visualizations for operational fraud monitoring dashboards.")


if __name__ == "__main__":
    try:
        detector = FraudOutlierDetection()
        detector.run()
    except Exception as e:
        print(f"Program failed with error: {e}")
