"""
fulldemo.py
Author: Vinaya Sathyanarayana

This program demonstrates various clustering techniques using synthetic credit card customer data.
It reads the syntheticdata.csv generated by syndata.py and performs clustering analyses:
- Distance-based (KMeans)
- Density-based (DBSCAN)
- Dimensionality reduction (PCA + KMeans)
- High-dimensional data clustering (Agglomerative Clustering)
- Comparison of models via evaluation metrics

Outputs include:
- Data preprocessing explanation
- Step-by-step clustering process
- Visualizations with interpretation
- Model performance comparison table

Instructions for Students:
- Ensure syntheticdata.csv is generated by syndata.py and present in the working directory
- Run this script to see clustering methods applied on financial data
- Modify parameters in the script to experience clustering behavior changes

Instructions for Banks:
- Helps segment customers for targeted marketing, risk, and fraud management
- Shows how clustering groups customers with similar financial behaviors

Extensive error handling and documentation included.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score
from sklearn.exceptions import NotFittedError

import warnings
warnings.filterwarnings('ignore')

def load_data(filename='syntheticdata.csv'):
    try:
        df = pd.read_csv(filename)
        print(f"Data loaded successfully from {filename}")
        return df
    except FileNotFoundError:
        print(f"Error: File {filename} not found. Please generate it using syndata.py")
        exit(1)
    except Exception as e:
        print(f"Error loading data: {e}")
        exit(1)

def preprocess_data(df):
    # Explanation:
    # We process numerical and categorical data to prepare for clustering.
    # Encode categorical variables and scale numerical features.
    
    df_clean = df.copy()

    # Drop columns not used for clustering - IDs, Name etc.
    df_clean.drop(['CustomerID', 'Name'], axis=1, inplace=True)

    # Encode categorical variables
    le_gender = LabelEncoder()
    df_clean['Gender'] = le_gender.fit_transform(df_clean['Gender'])
    le_card = LabelEncoder()
    df_clean['CardType'] = le_card.fit_transform(df_clean['CardType'])

    # Features for clustering
    features = df_clean.columns.tolist()
    
    # Standardize numerical features for equal weighting
    scaler = StandardScaler()
    df_scaled = scaler.fit_transform(df_clean)

    print("Data preprocessing complete: Categorical encoded, numerical features scaled.")
    return df_scaled, features

def kmeans_demo(data, features, n_clusters=4):
    print("\n--- KMeans Clustering Demonstration ---")
    kmeans = KMeans(n_clusters=n_clusters, random_state=42)
    clusters = kmeans.fit_predict(data)
    
    silhouette_avg = silhouette_score(data, clusters)
    print(f"KMeans: Number of clusters chosen = {n_clusters}")
    print(f"Silhouette Score (higher is better): {silhouette_avg:.4f}")

    # Visualize cluster centers in feature space using PCA reduction
    pca = PCA(n_components=2)
    data_2d = pca.fit_transform(data)
    
    plt.figure(figsize=(8,6))
    scatter = plt.scatter(data_2d[:,0], data_2d[:,1], c=clusters, cmap='viridis', s=10)
    plt.title(f'KMeans Clustering Visualization (n={n_clusters}) in 2D PCA space')
    plt.xlabel('PCA Component 1')
    plt.ylabel('PCA Component 2')
    plt.legend(*scatter.legend_elements(), title='Clusters')
    plt.show()

    print("Interpretation: Each color represents a cluster. Clusters group customers with similar financial profiles.\n")
    return clusters, silhouette_avg

def dbscan_demo(data, eps=1.5, min_samples=10):
    print("\n--- DBSCAN Clustering Demonstration ---")
    dbscan = DBSCAN(eps=eps, min_samples=min_samples)
    clusters = dbscan.fit_predict(data)

    # Noise is labeled as -1 by DBSCAN
    n_clusters = len(set(clusters)) - (1 if -1 in clusters else 0)
    n_noise = list(clusters).count(-1)
    if n_clusters > 0:
        silhouette_avg = silhouette_score(data[clusters != -1], clusters[clusters != -1])
    else:
        silhouette_avg = float('nan')

    print(f"DBSCAN: Number of clusters found (excluding noise) = {n_clusters}")
    print(f"Number of noise points = {n_noise}")
    print(f"Silhouette Score for clusters (excluding noise): {silhouette_avg:.4f}")

    # Visualize clusters in 2D PCA space
    pca = PCA(n_components=2)
    data_2d = pca.fit_transform(data)

    plt.figure(figsize=(8,6))
    plt.scatter(data_2d[clusters == -1, 0], data_2d[clusters == -1, 1], c='red', s=10, label='Noise')
    plt.scatter(data_2d[clusters != -1, 0], data_2d[clusters != -1, 1], c=clusters[clusters != -1], cmap='tab10', s=10)
    plt.title(f'DBSCAN Clustering Visualization in 2D PCA space')
    plt.xlabel('PCA Component 1')
    plt.ylabel('PCA Component 2')
    plt.legend()
    plt.show()

    print("Interpretation: Points labeled as red are noise/outliers. Clusters represent groups with similar data density.\n")
    return clusters, silhouette_avg, n_noise

def pca_kmeans_demo(data, features, n_clusters=4):
    print("\n--- PCA + KMeans Demonstration ---")
    pca = PCA(n_components=5)  # Reduce dimensionality while preserving variance
    data_pca = pca.fit_transform(data)
    print(f"Explained variance by 5 components: {sum(pca.explained_variance_ratio_):.2%}")

    kmeans = KMeans(n_clusters=n_clusters, random_state=42)
    clusters = kmeans.fit_predict(data_pca)
    silhouette_avg = silhouette_score(data_pca, clusters)
    print(f"KMeans on PCA-reduced data: Number of clusters = {n_clusters}")
    print(f"Silhouette Score: {silhouette_avg:.4f}")

    plt.figure(figsize=(8,6))
    scatter = plt.scatter(data_pca[:,0], data_pca[:,1], c=clusters, cmap='plasma', s=10)
    plt.title(f'KMeans on PCA-reduced data (2D plot of first two components)')
    plt.xlabel('PCA Component 1')
    plt.ylabel('PCA Component 2')
    plt.legend(*scatter.legend_elements(), title='Clusters')
    plt.show()

    print("Interpretation: PCA reduces dimensionality keeping maximum information, improving cluster separation.\n")
    return clusters, silhouette_avg

def agg_clustering_demo(data, n_clusters=4):
    print("\n--- Agglomerative Clustering Demonstration ---")
    agg = AgglomerativeClustering(n_clusters=n_clusters)
    clusters = agg.fit_predict(data)
    silhouette_avg = silhouette_score(data, clusters)
    print(f"Agglomerative Clustering: Number of clusters = {n_clusters}")
    print(f"Silhouette Score: {silhouette_avg:.4f}")

    # Visualize with PCA 2D plot
    pca = PCA(n_components=2)
    data_2d = pca.fit_transform(data)

    plt.figure(figsize=(8,6))
    scatter = plt.scatter(data_2d[:,0], data_2d[:,1], c=clusters, cmap='coolwarm', s=10)
    plt.title('Agglomerative Clustering Visualization in 2D PCA space')
    plt.xlabel('PCA Component 1')
    plt.ylabel('PCA Component 2')
    plt.legend(*scatter.legend_elements(), title='Clusters')
    plt.show()

    print("Interpretation: Hierarchical clusters show how customers merge stepwise based on similarity.\n")
    return clusters, silhouette_avg

def compare_models(metrics_dict):
    print("\n--- Model Comparison ---")
    df_compare = pd.DataFrame(metrics_dict).T
    df_compare = df_compare.rename(columns={'silhouette': 'Silhouette Score', 'noise': 'Noise Points (DBSCAN Only)'})
    print(df_compare.fillna('N/A'))
    print("\nInterpretation: Higher silhouette score indicates better defined clusters. DBSCAN also identifies noise.")

def main():
    df = load_data()
    data_scaled, features = preprocess_data(df)

    # Run clustering demonstrations
    kmeans_labels, kmeans_sil = kmeans_demo(data_scaled, features)
    dbscan_labels, dbscan_sil, dbscan_noise = dbscan_demo(data_scaled)
    pca_labels, pca_sil = pca_kmeans_demo(data_scaled, features)
    agg_labels, agg_sil = agg_clustering_demo(data_scaled)

    metrics = {
        'KMeans': {'silhouette': kmeans_sil, 'noise': None},
        'DBSCAN': {'silhouette': dbscan_sil, 'noise': dbscan_noise},
        'PCA + KMeans': {'silhouette': pca_sil, 'noise': None},
        'Agglomerative': {'silhouette': agg_sil, 'noise': None}
    }
    compare_models(metrics)

if __name__ == '__main__':
    try:
        main()
    except Exception as e:
        print(f"An error occurred during clustering demonstration: {e}")
