"""
Transaction fraud classification using supervised learning.
"""

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

np.random.seed(42)


def generate_transaction_data(n=8000):
    df = {
        "txn_id": [f"TX_{i:06d}" for i in range(n)],
        "amount": np.random.exponential(70, n).round(2),
        "hour": np.random.randint(0, 24, n),
        "day_of_week": np.random.randint(0, 7, n),
        "merchant_category": np.random.choice([0, 1, 2, 3], n),
        "user_age_days": np.random.randint(1, 3650, n),
        "prev_txn_freq_1h": np.random.poisson(1, n),
        "is_fraud": np.random.choice([0, 1], n, p=[0.97, 0.03]),
    }
    return pd.DataFrame(df)


def train_simple_classifier(df):
    features = ["amount", "hour", "day_of_week", "merchant_category", "user_age_days", "prev_txn_freq_1h"]
    X = df[features]
    y = df["is_fraud"]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
    model = RandomForestClassifier(n_estimators=50, random_state=42, n_jobs=-1)
    model.fit(X_train, y_train)
    acc = model.score(X_test, y_test)
    return model, acc


if __name__ == "__main__":
    txn = generate_transaction_data(5000)
    clf, accuracy = train_simple_classifier(txn)
    print(f"Fraud classification model trained. Test accuracy: {accuracy:.3f}")
    print("Output CSV with predictions can be generated by extending this script.")
