"""
Author: Vinaya Sathyanarayana

Credit Card Fraud Detection Classification Demo

This program demonstrates classification algorithms used for fraud detection on credit card transaction data.
It uses synthetic data generated by generate_synthetic_data.py.

Outputs include:
- Data exploration charts
- Performance metrics for Random Forest, SVM, Logistic Regression, and KNN
- Confusion matrices and feature importance plots
- Comparative evaluation table

Instructions and explanations are included to aid understanding and real-life application.

"""

import sys
import logging
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# Set up logging
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')


def load_data(filepath='syntheticdata.csv'):
    """Load the synthetic credit card transaction data"""
    try:
        data = pd.read_csv(filepath)
        logging.info(f'Data loaded successfully from {filepath}')
        return data
    except FileNotFoundError:
        logging.error(f'File {filepath} not found. Please generate synthetic data first using generate_synthetic_data.py')
        sys.exit(1)
    except Exception as e:
        logging.error(f'Error loading data: {str(e)}')
        sys.exit(1)


def preprocess_data(data):
    """
    Preprocess data:
    - Encode categorical features
    - Extract date/time features
    - Scale numeric features
    - Prepare feature matrix X and target y
    """
    try:
        df = data.copy()

        # Convert TransactionDate to datetime
        df['TransactionDate'] = pd.to_datetime(df['TransactionDate'], errors='coerce')
        df['TransactionYear'] = df['TransactionDate'].dt.year
        df['TransactionMonth'] = df['TransactionDate'].dt.month
        df['TransactionDay'] = df['TransactionDate'].dt.day

        # Convert TransactionTime to datetime time, then extract hour, minute
        df['TransactionTime'] = pd.to_datetime(df['TransactionTime'], format='%H:%M:%S', errors='coerce')
        df['TransactionHour'] = df['TransactionTime'].dt.hour
        df['TransactionMinute'] = df['TransactionTime'].dt.minute

        # Drop original date/time and non-informative columns (TransactionID, CardHolderName, CardNumber)
        df.drop(columns=['TransactionID', 'CardHolderName', 'CardNumber', 'TransactionDate', 'TransactionTime'], inplace=True)

        # Encode categorical variables: MerchantCategory, TransactionCity
        le_merchant = LabelEncoder()
        le_city = LabelEncoder()
        df['MerchantCategory_enc'] = le_merchant.fit_transform(df['MerchantCategory'])
        df['TransactionCity_enc'] = le_city.fit_transform(df['TransactionCity'])

        df.drop(columns=['MerchantCategory', 'TransactionCity'], inplace=True)

        # Features and target
        X = df.drop(columns=['IsFraud'])
        y = df['IsFraud']

        # Scale numeric features
        scaler = StandardScaler()
        numeric_features = ['TransactionAmount', 'TransactionYear', 'TransactionMonth', 'TransactionDay', 'TransactionHour', 'TransactionMinute']
        X[numeric_features] = scaler.fit_transform(X[numeric_features])

        return X, y, le_merchant, le_city, scaler

    except Exception as e:
        logging.error(f'Error in preprocessing data: {str(e)}')
        sys.exit(1)


def plot_class_distribution(y):
    """Plot the distribution of fraud vs non-fraud classes"""
    plt.figure(figsize=(6,4))
    sns.countplot(x=y)
    plt.title('Class Distribution (0=Non-Fraud, 1=Fraud)')
    plt.xlabel('IsFraud')
    plt.ylabel('Number of Transactions')
    plt.tight_layout()
    plt.show()
    print("The class distribution shows the imbalance: fraudulent transactions (class 1) are much fewer than non-fraudulent transactions (class 0). This is typical in fraud detection.")


def train_and_evaluate_models(X_train, X_test, y_train, y_test):
    """
    Train and evaluate multiple classifiers.
    Return results dictionary with classification reports and confusion matrices.
    """
    results = {}

    models = {
        'Random Forest': RandomForestClassifier(random_state=1234),
        'SVM': SVC(random_state=1234, probability=True),
        'Logistic Regression': LogisticRegression(random_state=1234, max_iter=1000),
        'KNN': KNeighborsClassifier()
    }

    for name, model in models.items():
        logging.info(f'Training {name}...')
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        acc = accuracy_score(y_test, y_pred)
        prec = precision_score(y_test, y_pred)
        rec = recall_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred)

        conf_mat = confusion_matrix(y_test, y_pred)

        report = classification_report(y_test, y_pred)

        results[name] = {
            'model': model,
            'accuracy': acc,
            'precision': prec,
            'recall': rec,
            'f1_score': f1,
            'confusion_matrix': conf_mat,
            'classification_report': report
        }

        logging.info(f'{name} - Accuracy: {acc:.4f}, Precision: {prec:.4f}, Recall: {rec:.4f}, F1 Score: {f1:.4f}')

    return results


def plot_confusion_matrix(conf_mat, title):
    """Plot a confusion matrix with annotations."""
    plt.figure(figsize=(5,4))
    sns.heatmap(conf_mat, annot=True, fmt='d', cmap='Blues')
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.title(title)
    plt.xticks([0.5,1.5], ['Non-Fraud (0)', 'Fraud (1)'])
    plt.yticks([0.5,1.5], ['Non-Fraud (0)', 'Fraud (1)'], rotation=0)
    plt.tight_layout()
    plt.show()
    print(f"The confusion matrix for {title} shows the count of true positives, true negatives, false positives, and false negatives. High true positive and true negative counts indicate good model performance.")


def plot_feature_importance(model, feature_names):
    """Plot feature importance for Random Forest model"""
    try:
        if hasattr(model, 'feature_importances_'):
            importances = model.feature_importances_
            indices = np.argsort(importances)[::-1]

            plt.figure(figsize=(8,5))
            sns.barplot(x=importances[indices], y=np.array(feature_names)[indices])
            plt.title('Feature Importance - Random Forest')
            plt.xlabel('Importance')
            plt.ylabel('Features')
            plt.tight_layout()
            plt.show()
            print("The feature importance graph shows which features contribute most to the fraud detection by the Random Forest model. Features with higher bars are more influential.")
        else:
            print("Feature importance not available for this model.")
    except Exception as e:
        logging.error(f"Error plotting feature importance: {str(e)}")


def print_comparison_table(results):
    """Print a table comparing evaluation metrics from different models."""
    try:
        df = pd.DataFrame(columns=['Model', 'Accuracy', 'Precision', 'Recall', 'F1 Score'])
        for model_name, metrics in results.items():
            df = df.append({
                'Model': model_name,
                'Accuracy': f"{metrics['accuracy']:.4f}",
                'Precision': f"{metrics['precision']:.4f}",
                'Recall': f"{metrics['recall']:.4f}",
                'F1 Score': f"{metrics['f1_score']:.4f}"
            }, ignore_index=True)
        print("\nModel Performance Comparison:\n")
        print(df.to_string(index=False))
    except Exception as e:
        logging.error(f"Error printing comparison table: {str(e)}")


def main():
    data = load_data()

    print("\nExploratory Data Analysis:")
    plot_class_distribution(data['IsFraud'])

    X, y, le_merchant, le_city, scaler = preprocess_data(data)

    # Split data 70% train, 30% test
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1234, stratify=y)

    results = train_and_evaluate_models(X_train, X_test, y_train, y_test)

    for model_name, res in results.items():
        print(f"\nClassification Report for {model_name}:")
        print(res['classification_report'])
        plot_confusion_matrix(res['confusion_matrix'], title=f'Confusion Matrix - {model_name}')
        if model_name == 'Random Forest':
            plot_feature_importance(res['model'], X.columns)

    print_comparison_table(results)

    print("\nInstructions for Students:")
    print("- Experiment with dataset size and fraud_ratio in generate_synthetic_data.py to see impact on model performance.")
    print("- Try tuning hyperparameters in this script for each algorithm to observe changes.")
    print("- Analyze confusion matrices to understand type I and type II errors in fraud detection.")
    print("- Interpret feature importance to identify key fraud indicators.")
    print("\nBanking Use Case:")
    print("- Banks can implement such models in real-time to flag suspicious credit card transactions.")
    print("- Model evaluations help select best performing classifiers for fraud alert systems.")
    print("- Understanding false positives and false negatives is vital to balance security and customer convenience.")

if __name__ == "__main__":
    main()
