"""
fulldemo.py
Author: Vinaya Sathyanarayana

Demonstration of selected pattern mining algorithms Apriori, FP-Growth, and PrefixSpan
on synthetic credit card transaction data generated by syndata.py.

Includes fixes for:
- FutureWarning on DataFrame.applymap deprecation
- DeprecationWarning on non-bool types in frequent pattern mining

Instructions:
Ensure requirements.txt is installed, including mlxtend and prefixspan.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from mlxtend.frequent_patterns import apriori, fpgrowth, association_rules
from prefixspan import PrefixSpan


class PatternMiningDemo:
    def __init__(self, datafile='syntheticdata.csv'):
        self.datafile = datafile
        self.df = None

    def load_data(self):
        self.df = pd.read_csv(self.datafile)
        print(f"Loaded {len(self.df)} transactions from {self.datafile}")

    def preprocess_transaction_data(self):
        # Prepare transaction dataset for Apriori and FP-Growth
        df = self.df.copy()
        df['Item'] = df['MerchantCategory'] + '_' + df['TransactionType']

        basket = (df.groupby(['CustomerID', 'Item'])['TransactionAmount']
                  .sum()
                  .unstack()
                  .reset_index()
                  .fillna(0)
                  .set_index('CustomerID'))

        # Fix for warnings: convert to boolean DataFrame
        basket_bool = (basket > 0)
        # Convert boolean DataFrame to int for visualization if needed
        # But keep basket_bool (bool) for mining algorithms to avoid DeprecationWarning
        print(f"Transaction-item matrix shape: {basket_bool.shape} with boolean dtype")
        return basket_bool

    def preprocess_sequence_data(self):
        # Prepare sequential dataset for PrefixSpan
        grouped = self.df.groupby('CustomerID')
        sequences = []

        for _, group in grouped:
            sorted_group = group.sort_values('TransactionDate')
            seq = sorted_group.apply(lambda row: f"{row['MerchantCategory']}_{row['TransactionType']}", axis=1).tolist()
            sequences.append(seq)

        print(f"Prepared sequence dataset with {len(sequences)} sequences")
        return sequences

    def run_apriori(self, basket, min_support=0.01):
        print("Running Apriori algorithm...")
        freq_items = apriori(basket, min_support=min_support, use_colnames=True)
        rules = association_rules(freq_items, metric="confidence", min_threshold=0.5)
        print(f"Apriori found {len(freq_items)} frequent itemsets and {len(rules)} rules.")
        return freq_items, rules

    def run_fpgrowth(self, basket, min_support=0.01):
        print("Running FP-Growth algorithm...")
        freq_items = fpgrowth(basket, min_support=min_support, use_colnames=True)
        rules = association_rules(freq_items, metric="confidence", min_threshold=0.5)
        print(f"FP-Growth found {len(freq_items)} frequent itemsets and {len(rules)} rules.")
        return freq_items, rules

    def run_prefixspan(self, sequences, min_support=0.01):
        print("Running PrefixSpan algorithm...")
        ps = PrefixSpan(sequences)
        min_sup_count = int(len(sequences) * min_support)
        results = ps.frequent(min_sup_count)
        print(f"PrefixSpan found {len(results)} sequential patterns with min support {min_sup_count}.")
        return results

    def plot_frequent_itemsets(self, freq_items, title):
        if freq_items.empty:
            print("No frequent itemsets to plot.")
            return
        freq_items = freq_items.sort_values(by='support', ascending=False).head(10)
        plt.figure(figsize=(10, 6))
        sns.barplot(x='support', y=freq_items['itemsets'].apply(lambda x: ', '.join(list(x))), data=freq_items)
        plt.title(title)
        plt.xlabel('Support')
        plt.ylabel('Frequent Itemsets')
        plt.tight_layout()
        plt.show()

    def plot_prefixspan_patterns(self, patterns, title, top_n=10):
        if not patterns:
            print("No sequential patterns to plot.")
            return
        patterns = sorted(patterns, key=lambda x: x[0], reverse=True)[:top_n]
        supports = [count for count, pattern in patterns]
        pattern_strs = [', '.join(pattern) for count, pattern in patterns]
        plt.figure(figsize=(10, 6))
        sns.barplot(x=supports, y=pattern_strs)
        plt.xlabel('Support Count')
        plt.title(title)
        plt.tight_layout()
        plt.show()

    def run_demo(self):
        self.load_data()

        basket = self.preprocess_transaction_data()
        sequences = self.preprocess_sequence_data()

        apriori_items, apriori_rules = self.run_apriori(basket)
        self.plot_frequent_itemsets(apriori_items, "Top 10 Frequent Itemsets by Apriori")

        fpgrowth_items, fpgrowth_rules = self.run_fpgrowth(basket)
        self.plot_frequent_itemsets(fpgrowth_items, "Top 10 Frequent Itemsets by FP-Growth")

        prefixspan_patterns = self.run_prefixspan(sequences)
        self.plot_prefixspan_patterns(prefixspan_patterns, "Top 10 Sequential Patterns by PrefixSpan")

        print("\nExplanations:")
        print("- Frequent itemsets reveal common combinations of merchant category and transaction type in transactions.")
        print("- Support indicates proportion of transactions containing the itemset.")
        print("- Association rules show relationships between itemsets.")
        print("- Sequential patterns capture time-ordered behavior of customers.")
        print("- These insights help banks with customer behavior profiling, fraud detection, and marketing.\n")


def main():
    demo = PatternMiningDemo()
    demo.run_demo()


if __name__ == '__main__':
    main()
